 
DROP TABLE IF EXISTS PORT;
DROP TABLE IF EXISTS PASSENGER;
DROP TABLE IF EXISTS OCCUPATION;
DROP TABLE IF EXISTS SERVICE;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS LIFEBOAT;
DROP TABLE IF EXISTS RECOVERY;
DROP TABLE IF EXISTS RESCUE;